### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by casey-c** [casey-c/egg#8]
Here's a collection of individual projects we need doing. I'll make individual issues for them all and update this post to connect them.

### Tree
- [x] [~~Copy constructors~~](https://github.com/casey-c/egg/issues/9)
- [x] [~~Destructors (memory deallocation)~~](https://github.com/casey-c/egg/issues/10)
- [x] [~~Move node() and surround with cut/double cut functions~~](https://github.com/casey-c/egg/issues/26)
- [x] [~~Add templates (implication, or, etc.)~~](https://github.com/casey-c/egg/issues/12)
- [x] [~~Multiple selection - no longer a post-release pipe dream, we need it for modification mode~~](https://github.com/casey-c/egg/issues/40)
- [x] [~~Remove functions for Tree~~](https://github.com/casey-c/egg/issues/11)
- [ ] [Depth tracking](https://github.com/casey-c/egg/issues/36)
- [ ] [Modification mode commands (iteration/deiteration, erasure, insertion, doublecuts)](https://github.com/casey-c/egg/issues/13)
- [ ] [Equality operations (required for modification mode, goal comparison - tricky to do)](https://github.com/casey-c/egg/issues/39)

### ProofTree
- [ ] [Basics - work with multiple TreeStates in a tree](https://github.com/casey-c/egg/issues/14)
- [ ] [Calling a modification function on the tree will make a new TreeState](https://github.com/casey-c/egg/issues/15)
- [ ] [Able to click on previous TreeState objects and manipulate through](https://github.com/casey-c/egg/issues/16)

### Command
- [x] [~~Class to implement the Command design pattern - every function call should go through this so that undo and redo are easily implementable~~](https://github.com/casey-c/egg/issues/17)
- [x] [~~Undo/Redo history. We need some kind of data structure in our main window that keeps track of all the commands used so that undo and redo are available.~~](https://github.com/casey-c/egg/issues/18)
- [ ] [Macros: save a long string of key presses to easily repeat later](https://github.com/casey-c/egg/issues/56)
- [ ] [Smarter repeat - maybe only repeat changes of the graph, not movement or other superficial commands](https://github.com/casey-c/egg/issues/55)
- [ ] [Add commands for formula input](https://github.com/casey-c/egg/issues/54)
- [ ] [Destructors / General cleanup and fix of memory leak issues, especially with cleared redo commands and detach commands](https://github.com/casey-c/egg/issues/44)

### Formula Input
- [x] [~~Better documentation, cleanup~~](https://github.com/casey-c/egg/issues/59)

### Grid
- [ ] [Destructors / memory clean up](https://github.com/casey-c/egg/issues/58)
- [ ] [Better layout instead of all in a straight line](https://github.com/casey-c/egg/issues/57)
- [x] [~~Better documentation, cleanup~~](https://github.com/casey-c/egg/issues/60)

### Graphics Canvas
- [x] [~~Need to start considering how to implement drawing the actual graph~~](https://github.com/casey-c/egg/issues/19)
- [ ] [Need a layout manager to actually convert between a TreeState and a visual state](https://github.com/casey-c/egg/issues/20)
